### ISSUE TITLE
ActivityInterface - Objects become pullable by any other object when rake is grasped

### ISSUE THREAD

**Issue by AlexAntn** [robotology/poeticon#151]
When the robot grasps the rake, objects that were pullable with the rake no longer appear as so, and are instead pullable by everything else (bun-bottom, bun-top, etc)

Ideally, the "pullable with" symbol wouldn't change when the tool is grasped

**Comment by gsaponaro** [comment]
@AlexAntn, I think this is now solved. Please reopen if not.
