### ISSUE TITLE
Commit praxInterface module (interface between PRAXICON and YARP)

### ISSUE THREAD

**Issue by gsaponaro** [robotology/poeticon#157]
Hi @vtikha, I suggest this module gets committed to the repository. It should probably be compiled only on WIN32 systems. Do you agree?

If you want, I can commit the version that we have on our Windows/PRAXICON laptop from the latest integration meeting.

**Comment by vtikha** [comment]
@gsaponaro agreed

**Comment by gsaponaro** [comment]
OK, I committed **praxiconInterface**.

Even though it will be used in Windows, I tried to compile it in Linux for testing. There were two problems, I solved the first one but not the second one.

First problem was:
```
/home/gsaponaro/NOBACKUP/poeticon_upstream/src/praxiconInterface/src/praxiconInterface.cpp: In member function ‘virtual bool PraxiconInterface::updateModule()’:
/home/gsaponaro/NOBACKUP/poeticon_upstream/src/praxiconInterface/src/praxiconInterface.cpp:78:19: error: no match for ‘operator!=’ (operand types are ‘yarp::os::Bottle’ and ‘long int’)
         if (speech!=NULL)
                   ^
```
which I solved by changing ```(speech!=NULL)``` to ```(!speech.isNull())```, where ```speech``` is a ```Bottle```.

Second compilation issue:
```
$ make
[ 25%] Building CXX object CMakeFiles/praxiconInterface.dir/src/stdsoap2.cpp.o
/home/gsaponaro/NOBACKUP/poeticon_upstream/src/praxiconInterface/src/stdsoap2.cpp:71:54: fatal error: include/iCub/PraxiconTreePortBinding.nsmap: No such file or directory
 #include "include/iCub/PraxiconTreePortBinding.nsmap"
```

I added ```include/iCub/PraxiconTreePortBinding.nsmap``` to ```CMakeLists.txt``` but it didn't help. Any clues? Can you try compiling?

**Comment by vtikha** [comment]
This module wa intenses to be used only in windows due to its depend

**Comment by gsaponaro** [comment]
Yep, this must run on the same (Windows) machine where the other PRAXICON modules run.

It was a stupid problem, I had put one of the files in the wrong location... fixed now, tested and it works. Thanks.
