### ISSUE TITLE
activityInterface pullableWith query gets stuck

### ISSUE THREAD

**Issue by gsaponaro** [robotology/poeticon#175]
Hi @vtikha, I ran into this situation with the latest version of all the software repositories:

* segmentation is good and stable (relying on ```lbpExtract```):
![2016-02-11segm](https://cloud.githubusercontent.com/assets/6716962/12993740/f8690d4c-d113-11e5-8609-06f1579be6d0.png)

* **activityInterface** responds correctly to these queries:
```
>>inHand rake
Response: none
>>reachableWith rake
Response: (bun-top left)
```

* however, it gets stuck on the ```pullableWith``` query (for any object), for example:
```
>>pullableWith rake
```

I restarted everything and reconnected just in case. The problem is consistent.

I also tried adding some debug prints in the **activityInterface** to locate the problem, and indeed it gets stuck in the first line of the function ```pullableWith(const string &objName)```, here:
```
    Bottle list = getToolLikeNames();
```

**Comment by vtikha** [comment]
Quick question as I have a small doubt. Did you connect correctly the new port ```lbpExtract``` to activity interface? As it get stuck while waiting for an image.. the port should be ```/lbpExtract/extractedlbp:o``` or even ```/lbpExtract/segmentedlbp:o```. Let me know before taking this any further.

**Comment by gsaponaro** [comment]
Hi @vtikha, I think that might be the problem, [our XML](https://github.com/robotology/poeticon/blob/master/app/scripts/poeticon%2B%2B_perception_mode.xml.template) does not have such a connection, sorry. Will confirm in one hour.

**Comment by gsaponaro** [comment]
I confirm that we are missing two connections: to ```/activityInterface/blobImg:i``` and ```/activityInterface/blobs:i```. Can you please tell me what goes to each of those? (which lbpExtract ports)

**Comment by vtikha** [comment]
```/lbpExtract/extractedlbp:o``` goes to ```/activityInterface/blobImg:i```
```/lbpExtract/blobs:o``` goes to ```/activityInterface/blobs:i```

**Comment by gsaponaro** [comment]
Problem solved, thanks! :)
Still, I would suggest to add some activityInterface internal checks (getInputCount()>0 etc.) to make the rpc server return [fail] when there are missing connections
