### ISSUE TITLE
activityInterface segmentation fault on ctrl-c

### ISSUE THREAD

**Issue by gsaponaro** [robotology/poeticon#176]
When **activityInterface** is initialized and its connections are made, it does not quit gracefully:

```
^C[try 1 of 3] Trying to shut down
RFModule closing
[INFO][closing] starting the shutdown procedure
Segmentation fault
```

**Comment by vtikha** [comment]
This might be caused by the missing connection in #175 as it the function is blocked and never gets out.

**Comment by gsaponaro** [comment]
Correct, now it quits properly.
