### ISSUE TITLE
error compiling poeticon tree

### ISSUE THREAD

**Issue by vtikha** [robotology/poeticon#187]
I have the following error compiling the poeticon tree after a recent update:
```
Linking CXX executable ../../bin/dummyWorldStateManager
CMakeFiles/dummyWorldStateManager.dir/src/DummyWorldStateMgrMain.cpp.o: In function `main':
DummyWorldStateMgrMain.cpp:(.text.startup+0xd2): undefined reference to `yarp::os::ResourceFinder::configure(int, char**)'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/dummyWorldStateManager] Error 1
```

**Comment by gsaponaro** [comment]
Thanks, I reproduced the problem, it seems to be related to [this yarp change](https://github.com/robotology/yarp/commit/169285ca68247e6d0affcd82ffc1a0f13ef808de) and is probably affecting other modules.

**Comment by vtikha** [comment]
fixed. Sorry my bad, compiling on a machine without an updated yarp + icub... remember to remove cache if you need to do it on your end.

**Comment by gsaponaro** [comment]
Ah, good, thanks (indeed I had to clean yarp cache and re-build everything to get it fixed).
